# Site settings
baseurl: /agi15ida
title: IDA @ AGI-15
email: vveitas@gmail.com
url: https://freedomandconstraint.github.io/agi15-ida
description: "Resulting from a collaboration between the AGI Society (which hosts the AGI conference series) and members of the Global Brain Institute at the Free University of Brussels, this Workshop will focus on issues related to distributed cognitive systems and their role in AGI research."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#4c4c4c'
  links: '#fff'

# Footer settings
footer: FaC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: 

# Build settings
markdown: kramdown
permalink: pretty
